#!/bin/csh
cd ..
set case_dir = "./cases/network/num_channels"

if (-e log.txt) then
	rm -f log.txt
endif

set sample = "{$case_dir}/Sample_100_nodes_20_demands.txt"
cp -f $sample ./Sample.txt

foreach channel_num (1 2 3 4 5 6 7 8)
	#foreach alg (lpr)
	foreach alg (lpr_ra pro_serving)
		cp -f ${case_dir}/{$alg}.py ./run.py

		if (-e result.txt) then
			rm -f result.txt
		endif
		#@ cnt = 1
		foreach line ("`cat Sample.txt`")
			#echo "SAMPLE: $cnt" >> log.txt
			#./run.py $line $num_nodes >> log.txt
			./run.py $line $channel_num
			#@ cnt += 1
		end
		mv -f result.txt $case_dir/result_{$alg}_{$channel_num}.txt
	end
end
rm -f ./Sample.txt
#EOF