#!/bin/csh
cd ..
set case_dir = "./cases/network/num_edges"

if (-e log.txt) then
	rm -f log.txt
endif
set sample = "{$case_dir}/Sample_100_nodes_20_demands.txt"
cp -f $sample ./Sample.txt
foreach alpha (0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1)
#foreach alpha (0.09 0.1)
	foreach alg (pro_serving)
		cp -f ${case_dir}/{$alg}.py ./run.py

		if (-e result.txt) then
			rm -f result.txt
		endif
		#@ cnt = 1
		foreach line ("`cat Sample.txt`")
			#echo "SAMPLE: $cnt" >> log.txt
			#./run.py $line $num_nodes >> log.txt
			./run.py $line $alpha
			#@ cnt += 1
		end
		mv -f result.txt $case_dir/result_{$alg}_{$alpha}.txt
	end
end
#EOF