#!/bin/csh
cd ..
set case_dir = "./cases/consumption_rate"

if (-e log.txt) then
	rm -f log.txt
endif

foreach rate (5 6 7 8 9 10)
	set sample = "{$case_dir}/Sample_100_nodes_20_demands_cs_{$rate}.txt"
	cp -f $sample ./Sample.txt
	foreach alg (ilp lpr lpr_ra pro_serving)
		cp -f ${case_dir}/{$alg}.py ./run.py

		if (-e result.txt) then
			rm -f result.txt
		endif
		#@ cnt = 1
		foreach line ("`cat Sample.txt`")
			#echo "SAMPLE: $cnt" >> log.txt
			#./run.py $line $num_nodes >> log.txt
			./run.py $line
			#@ cnt += 1
		end
		mv -f result.txt $case_dir/result_{$alg}_cs_{$rate}.txt
	end
end
#EOF