#!/bin/csh
cd ..
set case_dir = "./cases/capacity/nodes"
set nodes = 100
set demands = 20
set sample = "{$case_dir}/Sample_{$nodes}_nodes_{$demands}_demands.txt"
cp -f $sample ./Sample.txt
foreach alg (lpr lpr_ra pro_serving)
	cp -f $case_dir/{$alg}.py ./run.py
	sed -i "/nov =/s/num_nodes/$nodes/" run.py
	rm -f agg_result_m.txt agg_result_j.txt agg_result_ttk.txt
	foreach node_cap (20 30 40 50 60 70 80)
		rm -f result_m.txt result_j.txt result_ttk.txt
		foreach line ("`cat Sample.txt`")
			./run.py $line $node_cap
		end
		set avr = `./agg.py result_m.txt`
		echo "$node_cap $avr" >> agg_result_m.txt
		set avr = `./agg.py result_j.txt`
		echo "$node_cap $avr" >> agg_result_j.txt
		set avr = `./agg.py result_ttk.txt`
		echo "$node_cap $avr" >> agg_result_ttk.txt
		mv -f result_m.txt $case_dir/result_m_{$alg}_{$node_cap}.txt
		mv -f result_j.txt $case_dir/result_j_{$alg}_{$node_cap}.txt
		mv -f result_ttk.txt $case_dir/result_ttk_{$alg}_{$node_cap}.txt
		end
	mv -f agg_result_m.txt $case_dir/agg_result_m_{$alg}.txt
	mv -f agg_result_j.txt $case_dir/agg_result_j_{$alg}.txt
	mv -f agg_result_ttk.txt $case_dir/agg_result_ttk_{$alg}.txt
end
rm -f run.py Sample.txt
#EOF