#!/bin/csh
cd ..
set case_dir = "./cases/network/num_nodes"

if (-e log.txt) then
	rm -f log.txt
endif

#foreach num_nodes (100 150 200 250 300)
foreach num_nodes (50 100 150 200 250 300)
	set sample = "{$case_dir}/Sample_{$num_nodes}_nodes_20_demands.txt"
	cp -f $sample ./Sample.txt
	#foreach alg (lpr lpr_ra)
	foreach alg (pro_serving)
		cp -f ${case_dir}/{$alg}.py ./run.py

		if (-e result.txt) then
			rm -f result.txt
		endif
		#@ cnt = 1
		foreach line ("`cat Sample.txt`")
			#echo "SAMPLE: $cnt" >> log.txt
			#./run.py $line $num_nodes >> log.txt
			./run.py $line $num_nodes
			#@ cnt += 1
		end
		mv -f result.txt $case_dir/result_{$alg}_{$num_nodes}.txt
	end
end
#EOF